apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.azureidentityBinding }}
  namespace: {{ .Values.namespace }}
spec:
  azureIdentity: {{ .Values.azureidentitylabels }}
  selector: {{ .Values.azureidentitylabels }}